name: Execute
on: push
jobs:
  exec-jvm-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Execute .kt and .java files
        run: ./run.sh
      - name: Store artifacts
        uses: actions/upload-artifact@v1
        with:
          name: jvm-test-reports
          path: jvm-logs.txt

  exec-python-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Execute .py files
        run: |
          chmod +x ./python-run.sh
          ./python-run.sh
      - name: Store artifacts
        uses: actions/upload-artifact@v1
        with:
          name: python-test-reports
          path: python-logs.txt

  aggregate-logs:
    name: Aggregate logs & fail if not empty
    runs-on: ubuntu-latest
    needs: [ exec-python-files, exec-jvm-files ]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: jvm-test-reports
          path: ~/logs
      - uses: actions/download-artifact@v2
        with:
          name: python-test-reports
          path: ~/logs
      - name: Fail if not empty
        run: |
          touch agg-logs.txt
          ls -la ~/logs
          for i in ~/logs/*.txt; do
            echo "Reading logs $i"
            if [ -s "$i" ]; then
              cat "$i" >> agg-logs.txt;
              echo \ >> agg-logs.txt;
            else
              echo "No contents in $i"
            fi
            if [ -s agg-logs.txt ]; then
              cat agg-logs.txt;
              exit 1;
            else
              echo "Build passed" >> agg-logs.txt;
            fi
          done
      - name: Store artifacts
        uses: actions/upload-artifact@v1
        with:
          name: aggregate-logs-report.txt
          path: agg-logs.txt